"""initial clinic schema

Revision ID: 0f97a0a6fd44
Revises: 
Create Date: 2026-07-19 10:02:19.931382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f97a0a6fd44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actes_medicaux',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('duree_minutes', sa.Integer(), nullable=False),
    sa.Column('prix_base', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('protocole', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs_medicaux',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_medicaux_patient_id'), 'audit_logs_medicaux', ['patient_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_medicaux_utilisateur_id'), 'audit_logs_medicaux', ['utilisateur_id'], unique=False)
    op.create_index('ix_audit_patient_date', 'audit_logs_medicaux', ['patient_id', 'created_at'], unique=False)
    op.create_index('ix_audit_user_date', 'audit_logs_medicaux', ['utilisateur_id', 'created_at'], unique=False)
    op.create_table('categories_depenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('icone', sa.String(length=10), nullable=True),
    sa.Column('couleur', sa.String(length=7), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('budget_mensuel', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('clinic_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_settings_key'), 'clinic_settings', ['key'], unique=True)
    op.create_table('produits_injectables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('fabricant', sa.String(length=200), nullable=True),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('reference_fabricant', sa.String(length=100), nullable=True),
    sa.Column('unite', sa.String(length=20), nullable=False),
    sa.Column('prix_achat', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('prix_vente', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('stock_actuel', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_minimum', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_alerte', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('temperature_conservation', sa.String(length=50), nullable=True),
    sa.Column('conditions_stockage', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produits_injectables_nom'), 'produits_injectables', ['nom'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('photo_profil_url', sa.String(length=500), nullable=True),
    sa.Column('taux_commission', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('agenda_color', sa.String(length=7), nullable=True),
    sa.Column('specialite', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_utilisateurs_clinic_email', 'utilisateurs', ['clinic_id', 'email'], unique=False)
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('campagnes_marketing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('segment_cible', sa.JSON(), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('date_envoi_planifiee', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('nb_envoyes', sa.Integer(), nullable=False),
    sa.Column('nb_ouverts', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidatures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('poste', sa.String(length=200), nullable=False),
    sa.Column('nom_candidat', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('cv_url', sa.String(length=500), nullable=True),
    sa.Column('lettre_url', sa.String(length=500), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('notes_rh', sa.Text(), nullable=True),
    sa.Column('date_entretien', sa.DateTime(), nullable=True),
    sa.Column('evaluateur_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluateur_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lots_injectables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('numero_lot', sa.String(length=100), nullable=False),
    sa.Column('date_fabrication', sa.Date(), nullable=True),
    sa.Column('date_expiration', sa.Date(), nullable=False),
    sa.Column('quantite_initiale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantite_restante', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fournisseur', sa.String(length=200), nullable=True),
    sa.Column('date_reception', sa.Date(), nullable=True),
    sa.Column('prix_achat_lot', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('certificat_conformite_url', sa.String(length=500), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('barcode_url', sa.String(length=500), nullable=True),
    sa.Column('label_url', sa.String(length=500), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['produits_injectables.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lot_expiration_statut', 'lots_injectables', ['date_expiration', 'statut'], unique=False)
    op.create_index(op.f('ix_lots_injectables_date_expiration'), 'lots_injectables', ['date_expiration'], unique=False)
    op.create_index(op.f('ix_lots_injectables_numero_lot'), 'lots_injectables', ['numero_lot'], unique=True)
    op.create_index(op.f('ix_lots_injectables_produit_id'), 'lots_injectables', ['produit_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('genre', sa.String(length=10), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('adresse', sa.String(length=300), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('groupe_sanguin', sa.String(length=5), nullable=True),
    sa.Column('allergies_enc', sa.Text(), nullable=True),
    sa.Column('antecedents_medicaux_enc', sa.Text(), nullable=True),
    sa.Column('contre_indications_enc', sa.Text(), nullable=True),
    sa.Column('note_interne_enc', sa.Text(), nullable=True),
    sa.Column('photo_profil_url', sa.String(length=500), nullable=True),
    sa.Column('source_acquisition', sa.String(length=50), nullable=True),
    sa.Column('commercial_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_phone', sa.String(length=20), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('points_fidelite', sa.Integer(), nullable=False),
    sa.Column('niveau_fidelite', sa.String(length=10), nullable=False),
    sa.Column('derniere_visite', sa.Date(), nullable=True),
    sa.Column('consentement_rgpd_signe_le', sa.DateTime(), nullable=True),
    sa.Column('consentement_marketing', sa.Boolean(), nullable=False),
    sa.Column('anonymized_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patients_clinic_niveau', 'patients', ['clinic_id', 'niveau_fidelite'], unique=False)
    op.create_index('ix_patients_clinic_nom', 'patients', ['clinic_id', 'nom'], unique=False)
    op.create_index('ix_patients_clinic_telephone', 'patients', ['clinic_id', 'telephone'], unique=False)
    op.create_index(op.f('ix_patients_nom'), 'patients', ['nom'], unique=False)
    op.create_index(op.f('ix_patients_prenom'), 'patients', ['prenom'], unique=False)
    op.create_index(op.f('ix_patients_telephone'), 'patients', ['telephone'], unique=True)
    op.create_index(op.f('ix_patients_whatsapp_phone'), 'patients', ['whatsapp_phone'], unique=False)
    op.create_table('consentements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('acte_id', sa.Integer(), nullable=True),
    sa.Column('type_consentement', sa.String(length=50), nullable=False),
    sa.Column('contenu_signe', sa.Text(), nullable=True),
    sa.Column('signe_le', sa.DateTime(), nullable=False),
    sa.Column('methode_signature', sa.String(length=50), nullable=False),
    sa.Column('signature_base64', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('est_valide', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acte_id'], ['actes_medicaux.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consentements_patient_id'), 'consentements', ['patient_id'], unique=False)
    op.create_table('depenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('categorie_id', sa.Integer(), nullable=True),
    sa.Column('fournisseur', sa.String(length=200), nullable=True),
    sa.Column('titre', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('montant_ht', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('taux_tva', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('montant_tva', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('montant_ttc', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('date_depense', sa.Date(), nullable=False),
    sa.Column('periode_comptable', sa.Date(), nullable=False),
    sa.Column('mode_paiement', sa.String(length=50), nullable=True),
    sa.Column('reference_paiement', sa.String(length=100), nullable=True),
    sa.Column('facture_scan_url', sa.String(length=500), nullable=True),
    sa.Column('facture_scan_statut', sa.String(length=20), nullable=False),
    sa.Column('extraction_ia', sa.JSON(), nullable=True),
    sa.Column('lot_injectable_id', sa.Integer(), nullable=True),
    sa.Column('valide_par_id', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories_depenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_injectable_id'], ['lots_injectables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['valide_par_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_depenses_date_depense'), 'depenses', ['date_depense'], unique=False)
    op.create_index(op.f('ix_depenses_periode_comptable'), 'depenses', ['periode_comptable'], unique=False)
    op.create_table('fidelite_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('solde_apres', sa.Integer(), nullable=False),
    sa.Column('motif', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fidelite_transactions_patient_id'), 'fidelite_transactions', ['patient_id'], unique=False)
    op.create_table('rendez_vous',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('praticien_id', sa.Integer(), nullable=False),
    sa.Column('acte_id', sa.Integer(), nullable=True),
    sa.Column('date_heure_debut', sa.DateTime(), nullable=False),
    sa.Column('date_heure_fin', sa.DateTime(), nullable=True),
    sa.Column('salle', sa.String(length=50), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('notes_pre_acte', sa.Text(), nullable=True),
    sa.Column('notes_post_acte', sa.Text(), nullable=True),
    sa.Column('rappel_j1_envoye', sa.Boolean(), nullable=False),
    sa.Column('rappel_h2_envoye', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acte_id'], ['actes_medicaux.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['praticien_id'], ['utilisateurs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rdv_clinic_date', 'rendez_vous', ['clinic_id', 'date_heure_debut'], unique=False)
    op.create_index('ix_rdv_patient_date', 'rendez_vous', ['patient_id', 'date_heure_debut'], unique=False)
    op.create_index('ix_rdv_praticien_date', 'rendez_vous', ['praticien_id', 'date_heure_debut'], unique=False)
    op.create_index(op.f('ix_rendez_vous_date_heure_debut'), 'rendez_vous', ['date_heure_debut'], unique=False)
    op.create_table('series_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('nom_serie', sa.String(length=200), nullable=False),
    sa.Column('zone_anatomique', sa.String(length=50), nullable=True),
    sa.Column('acte_id', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acte_id'], ['actes_medicaux.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_photos_patient_id'), 'series_photos', ['patient_id'], unique=False)
    op.create_table('dossiers_medicaux',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('praticien_id', sa.Integer(), nullable=False),
    sa.Column('rdv_id', sa.Integer(), nullable=True),
    sa.Column('acte_id', sa.Integer(), nullable=True),
    sa.Column('date_acte', sa.DateTime(), nullable=False),
    sa.Column('zones_traitees', sa.JSON(), nullable=True),
    sa.Column('produits_utilises', sa.JSON(), nullable=True),
    sa.Column('observations_enc', sa.Text(), nullable=True),
    sa.Column('effets_secondaires', sa.Text(), nullable=True),
    sa.Column('satisfaction_patient', sa.Integer(), nullable=True),
    sa.Column('suivi_requis', sa.Boolean(), nullable=False),
    sa.Column('date_suivi_recommandee', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acte_id'], ['actes_medicaux.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['praticien_id'], ['utilisateurs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rdv_id'], ['rendez_vous.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dossier_patient_date', 'dossiers_medicaux', ['patient_id', 'date_acte'], unique=False)
    op.create_index(op.f('ix_dossiers_medicaux_date_acte'), 'dossiers_medicaux', ['date_acte'], unique=False)
    op.create_index(op.f('ix_dossiers_medicaux_patient_id'), 'dossiers_medicaux', ['patient_id'], unique=False)
    op.create_table('factures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('rdv_id', sa.Integer(), nullable=True),
    sa.Column('numero_facture', sa.String(length=50), nullable=False),
    sa.Column('date_emission', sa.Date(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('actes', sa.JSON(), nullable=True),
    sa.Column('produits', sa.JSON(), nullable=True),
    sa.Column('sous_total', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('taux_tva', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('montant_tva', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('total_ttc', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('remise_globale_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('mode_paiement', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rdv_id'], ['rendez_vous.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facture_clinic_date', 'factures', ['clinic_id', 'date_emission'], unique=False)
    op.create_index('ix_facture_clinic_statut', 'factures', ['clinic_id', 'statut'], unique=False)
    op.create_index(op.f('ix_factures_numero_facture'), 'factures', ['numero_facture'], unique=True)
    op.create_index(op.f('ix_factures_patient_id'), 'factures', ['patient_id'], unique=False)
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('commercial_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('facture_id', sa.Integer(), nullable=False),
    sa.Column('montant_ca', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('taux_commission', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('montant_commission', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('periode_mois', sa.Date(), nullable=False),
    sa.Column('validee_par_id', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_id'], ['utilisateurs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['facture_id'], ['factures.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validee_par_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_commercial_id'), 'commissions', ['commercial_id'], unique=False)
    op.create_index(op.f('ix_commissions_periode_mois'), 'commissions', ['periode_mois'], unique=False)
    op.create_table('photos_clinic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('date_prise', sa.DateTime(), nullable=False),
    sa.Column('zone_anatomique', sa.String(length=50), nullable=True),
    sa.Column('angle_prise', sa.String(length=20), nullable=True),
    sa.Column('url_stockage', sa.String(length=500), nullable=False),
    sa.Column('url_thumbnail', sa.String(length=500), nullable=True),
    sa.Column('hash_fichier', sa.String(length=64), nullable=True),
    sa.Column('taille_octets', sa.Integer(), nullable=True),
    sa.Column('visible_patient', sa.Boolean(), nullable=False),
    sa.Column('visible_marketing', sa.Boolean(), nullable=False),
    sa.Column('filigrane_applique', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('prise_par_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('raison_suppression', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers_medicaux.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prise_par_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['serie_id'], ['series_photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_photo_patient_type', 'photos_clinic', ['patient_id', 'type'], unique=False)
    op.create_index('ix_photo_patient_zone', 'photos_clinic', ['patient_id', 'zone_anatomique'], unique=False)
    op.create_index(op.f('ix_photos_clinic_patient_id'), 'photos_clinic', ['patient_id'], unique=False)
    op.create_table('utilisations_lot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('praticien_id', sa.Integer(), nullable=False),
    sa.Column('date_utilisation', sa.DateTime(), nullable=False),
    sa.Column('quantite_utilisee', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers_medicaux.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['lots_injectables.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['praticien_id'], ['utilisateurs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisations_lot_lot_id'), 'utilisations_lot', ['lot_id'], unique=False)
    op.create_index(op.f('ix_utilisations_lot_patient_id'), 'utilisations_lot', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilisations_lot_patient_id'), table_name='utilisations_lot')
    op.drop_index(op.f('ix_utilisations_lot_lot_id'), table_name='utilisations_lot')
    op.drop_table('utilisations_lot')
    op.drop_index(op.f('ix_photos_clinic_patient_id'), table_name='photos_clinic')
    op.drop_index('ix_photo_patient_zone', table_name='photos_clinic')
    op.drop_index('ix_photo_patient_type', table_name='photos_clinic')
    op.drop_table('photos_clinic')
    op.drop_index(op.f('ix_commissions_periode_mois'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_commercial_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_factures_patient_id'), table_name='factures')
    op.drop_index(op.f('ix_factures_numero_facture'), table_name='factures')
    op.drop_index('ix_facture_clinic_statut', table_name='factures')
    op.drop_index('ix_facture_clinic_date', table_name='factures')
    op.drop_table('factures')
    op.drop_index(op.f('ix_dossiers_medicaux_patient_id'), table_name='dossiers_medicaux')
    op.drop_index(op.f('ix_dossiers_medicaux_date_acte'), table_name='dossiers_medicaux')
    op.drop_index('ix_dossier_patient_date', table_name='dossiers_medicaux')
    op.drop_table('dossiers_medicaux')
    op.drop_index(op.f('ix_series_photos_patient_id'), table_name='series_photos')
    op.drop_table('series_photos')
    op.drop_index(op.f('ix_rendez_vous_date_heure_debut'), table_name='rendez_vous')
    op.drop_index('ix_rdv_praticien_date', table_name='rendez_vous')
    op.drop_index('ix_rdv_patient_date', table_name='rendez_vous')
    op.drop_index('ix_rdv_clinic_date', table_name='rendez_vous')
    op.drop_table('rendez_vous')
    op.drop_index(op.f('ix_fidelite_transactions_patient_id'), table_name='fidelite_transactions')
    op.drop_table('fidelite_transactions')
    op.drop_index(op.f('ix_depenses_periode_comptable'), table_name='depenses')
    op.drop_index(op.f('ix_depenses_date_depense'), table_name='depenses')
    op.drop_table('depenses')
    op.drop_index(op.f('ix_consentements_patient_id'), table_name='consentements')
    op.drop_table('consentements')
    op.drop_index(op.f('ix_patients_whatsapp_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_telephone'), table_name='patients')
    op.drop_index(op.f('ix_patients_prenom'), table_name='patients')
    op.drop_index(op.f('ix_patients_nom'), table_name='patients')
    op.drop_index('ix_patients_clinic_telephone', table_name='patients')
    op.drop_index('ix_patients_clinic_nom', table_name='patients')
    op.drop_index('ix_patients_clinic_niveau', table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_lots_injectables_produit_id'), table_name='lots_injectables')
    op.drop_index(op.f('ix_lots_injectables_numero_lot'), table_name='lots_injectables')
    op.drop_index(op.f('ix_lots_injectables_date_expiration'), table_name='lots_injectables')
    op.drop_index('ix_lot_expiration_statut', table_name='lots_injectables')
    op.drop_table('lots_injectables')
    op.drop_table('candidatures')
    op.drop_table('campagnes_marketing')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_index('ix_utilisateurs_clinic_email', table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_produits_injectables_nom'), table_name='produits_injectables')
    op.drop_table('produits_injectables')
    op.drop_index(op.f('ix_clinic_settings_key'), table_name='clinic_settings')
    op.drop_table('clinic_settings')
    op.drop_table('categories_depenses')
    op.drop_index('ix_audit_user_date', table_name='audit_logs_medicaux')
    op.drop_index('ix_audit_patient_date', table_name='audit_logs_medicaux')
    op.drop_index(op.f('ix_audit_logs_medicaux_utilisateur_id'), table_name='audit_logs_medicaux')
    op.drop_index(op.f('ix_audit_logs_medicaux_patient_id'), table_name='audit_logs_medicaux')
    op.drop_table('audit_logs_medicaux')
    op.drop_table('actes_medicaux')
    # ### end Alembic commands ###
