"""fix_missing_schema_fields

Revision ID: 261421ffceed
Revises: 20260813_tenant_settings_schema
Create Date: 2026-08-15 03:49:42.226432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261421ffceed'
down_revision: Union[str, None] = '20260813_tenant_settings_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratoires_partenaires',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('contact_nom', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('site_web', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs_financial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('entite_type', sa.String(length=50), nullable=False),
    sa.Column('entite_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('valeur_avant', sa.JSON(), nullable=True),
    sa.Column('valeur_apres', sa.JSON(), nullable=True),
    sa.Column('modifie_par_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['modifie_par_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delegues_medicaux',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('labo_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('prenom', sa.String(length=200), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('specialite', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['labo_id'], ['laboratoires_partenaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qms_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('contenu_markdown', sa.Text(), nullable=True),
    sa.Column('fichier_url', sa.String(length=500), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visites_delegues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('delegue_id', sa.Integer(), nullable=False),
    sa.Column('medecin_id', sa.Integer(), nullable=True),
    sa.Column('date_visite', sa.DateTime(), nullable=False),
    sa.Column('objet', sa.String(length=255), nullable=False),
    sa.Column('compte_rendu', sa.Text(), nullable=True),
    sa.Column('echantillons_recus', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delegue_id'], ['delegues_medicaux.id'], ),
    sa.ForeignKeyConstraint(['medecin_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_scribe_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('praticien_id', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('transcription_brute', sa.Text(), nullable=True),
    sa.Column('notes_structurees_soap', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers_medicaux.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['praticien_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dossiers_medicaux', sa.Column('statut_facturation', sa.String(length=20), nullable=False))
    op.add_column('dossiers_medicaux', sa.Column('actes_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dossiers_medicaux', 'actes_details')
    op.drop_column('dossiers_medicaux', 'statut_facturation')
    op.drop_table('medical_scribe_sessions')
    op.drop_table('visites_delegues')
    op.drop_table('qms_documents')
    op.drop_table('delegues_medicaux')
    op.drop_table('audit_logs_financial')
    op.drop_table('laboratoires_partenaires')
    # ### end Alembic commands ###
