"""add social crm tables

Revision ID: 2bfa8a61841c
Revises: 0f97a0a6fd44
Create Date: 2026-07-19 23:03:25.888640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bfa8a61841c'
down_revision: Union[str, None] = '0f97a0a6fd44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('plateforme', sa.String(length=20), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('date_publication_prevue', sa.DateTime(), nullable=True),
    sa.Column('date_publication_reelle', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('erreur', sa.String(length=300), nullable=True),
    sa.Column('plateforme_post_id', sa.String(length=255), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('commentaires', sa.Integer(), nullable=False),
    sa.Column('partages', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_posts_clinic_plateforme', 'social_posts', ['clinic_id', 'plateforme'], unique=False)
    op.create_index('ix_social_posts_clinic_statut', 'social_posts', ['clinic_id', 'statut'], unique=False)
    op.create_table('social_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('plateforme', sa.String(length=20), nullable=False),
    sa.Column('contact_id', sa.String(length=255), nullable=False),
    sa.Column('contact_nom', sa.String(length=200), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('reponse_auto_envoyee', sa.Boolean(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_social_messages_clinic_plateforme', 'social_messages', ['clinic_id', 'plateforme'], unique=False)
    op.create_index('ix_social_messages_clinic_statut', 'social_messages', ['clinic_id', 'statut'], unique=False)
    op.create_index(op.f('ix_social_messages_contact_id'), 'social_messages', ['contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_messages_contact_id'), table_name='social_messages')
    op.drop_index('ix_social_messages_clinic_statut', table_name='social_messages')
    op.drop_index('ix_social_messages_clinic_plateforme', table_name='social_messages')
    op.drop_table('social_messages')
    op.drop_index('ix_social_posts_clinic_statut', table_name='social_posts')
    op.drop_index('ix_social_posts_clinic_plateforme', table_name='social_posts')
    op.drop_table('social_posts')
    # ### end Alembic commands ###
