"""add equipe messages table

Revision ID: b2c3d4e5f6g7
Revises: 62f1dcc65ced
Create Date: 2026-07-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6g7'
down_revision: Union[str, None] = '62f1dcc65ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipe_messages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('clinic_id', sa.Integer(), nullable=False),
        sa.Column('expediteur_id', sa.Integer(), nullable=False),
        sa.Column('destinataire_id', sa.Integer(), nullable=False),
        sa.Column('sujet', sa.String(length=200), nullable=False),
        sa.Column('contenu', sa.Text(), nullable=False),
        sa.Column('lu', sa.Boolean(), nullable=False),
        sa.Column('lu_a', sa.DateTime(), nullable=True),
        sa.Column('cree_a', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['expediteur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['destinataire_id'], ['utilisateurs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equipe_messages_clinic_expediteur', 'equipe_messages', ['clinic_id', 'expediteur_id'], unique=False)
    op.create_index('ix_equipe_messages_clinic_destinataire', 'equipe_messages', ['clinic_id', 'destinataire_id'], unique=False)
    op.create_index('ix_equipe_messages_destinataire_lu', 'equipe_messages', ['destinataire_id', 'lu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_equipe_messages_destinataire_lu', table_name='equipe_messages')
    op.drop_index('ix_equipe_messages_clinic_destinataire', table_name='equipe_messages')
    op.drop_index('ix_equipe_messages_clinic_expediteur', table_name='equipe_messages')
    op.drop_table('equipe_messages')
    # ### end Alembic commands ###
