"""catch_missing_models_and_fields

Revision ID: ca7adcd5a7ff
Revises: bloc8b_avis_plateforme_enum
Create Date: 2026-07-30 18:35:17.122837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ca7adcd5a7ff'
down_revision: Union[str, None] = 'bloc8b_avis_plateforme_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_clinic_date', 'workflow_audit_logs', ['clinic_id', 'created_at'], unique=False)
    op.create_index('ix_audit_workflow_exec', 'workflow_audit_logs', ['workflow_id', 'execution_id'], unique=False)
    op.create_table('taches_internes_assistant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('creee_par_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priorite', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creee_par_id'], ['utilisateurs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_taches_assistant_assignee', 'taches_internes_assistant', ['assignee_id'], unique=False)
    op.create_index('ix_taches_assistant_clinic_statut', 'taches_internes_assistant', ['clinic_id', 'statut'], unique=False)
    op.create_index('ix_taches_assistant_patient', 'taches_internes_assistant', ['patient_id'], unique=False)
    
    with op.batch_alter_table('alertes_securite', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('avis_clients', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('channel_configs', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('messages_envoyes_aujourdhui',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('channel_events', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_channel_events_message_id'), ['message_id'], unique=False)

    with op.batch_alter_table('commandes_assistant', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('intent_detecte',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('outil_appele',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('role_applique',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('parametres_appel',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('tool_payload_json',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index('ix_commande_outil')
        batch_op.drop_index('ix_commande_utilisateur')
        batch_op.create_index('ix_commandes_assistant_outil', ['clinic_id', 'outil_appele'], unique=False)
        batch_op.create_index('ix_commandes_assistant_utilisateur', ['clinic_id', 'utilisateur_id'], unique=False)
        batch_op.create_foreign_key('fk_commandes_utilisateur', 'utilisateurs', ['utilisateur_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('confirmations_sensibles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index('ix_confirmations_clinic_statut', ['clinic_id', 'statut'], unique=False)
        batch_op.create_index(batch_op.f('ix_confirmations_sensibles_code_confirmation'), ['code_confirmation'], unique=False)
        batch_op.create_index('ix_confirmations_session', ['session_id'], unique=False)
        batch_op.create_foreign_key('fk_confirmations_session', 'sessions_assistant', ['session_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('nb_messages',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_conversations_contact_external_id'), ['contact_external_id'], unique=False)

    with op.batch_alter_table('factures', schema=None) as batch_op:
        batch_op.alter_column('date_emission',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('messages_omnicanal', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('type_message',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('nb_retries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('max_retries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('reponse_auto',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_messages_omnicanal_conversation_id'), ['conversation_id'], unique=False)

    with op.batch_alter_table('numeros_whitelist', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_constraint('uq_numeros_whitelist_numero', type_='unique')
        batch_op.create_index(batch_op.f('ix_numeros_whitelist_numero'), ['numero'], unique=True)
        batch_op.create_index('ix_whitelist_clinic_statut', ['clinic_id', 'statut'], unique=False)

    with op.batch_alter_table('sessions_assistant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilisateur_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contexte_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_mfa_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('nb_tours',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('nb_erreurs',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index('ix_sessions_assistant_numero', ['clinic_id', 'numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_assistant_token_session'), ['token_session'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_assistant_whitelist_id'), ['whitelist_id'], unique=False)
        batch_op.create_foreign_key('fk_sessions_utilisateur', 'utilisateurs', ['utilisateur_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('simulations_ia', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.alter_column('mfa_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('mfa_failed_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('workflow_actions_log', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('workflow_schedules', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('execution_count_today',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('workflow_templates', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('clinic_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Downgrade is not strictly required for this verification but good practice
    pass
