"""add consommables tables

Revision ID: e1a2b3c4d5e6
Revises: 62f1dcc65ced
Create Date: 2026-07-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a2b3c4d5e6'
down_revision = '62f1dcc65ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consommables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=False),
    sa.Column('unite', sa.String(length=50), nullable=False),
    sa.Column('stock_actuel', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('seuil_alerte', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_minimum', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consommables_nom'), 'consommables', ['nom'], unique=False)
    
    op.create_table('mouvements_consommables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('consommable_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_mouvement', sa.DateTime(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['consommable_id'], ['consommables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mouvements_consommables')
    op.drop_index(op.f('ix_consommables_nom'), table_name='consommables')
    op.drop_table('consommables')
    # ### end Alembic commands ###
